// This file is automatically generated by qtc from "emails.apex.hbs.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line emails.apex.hbs.qtpl:1
package apex

//line emails.apex.hbs.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line emails.apex.hbs.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line emails.apex.hbs.qtpl:1
func StreamApexEmailsTemplate(qw422016 *qt422016.Writer, data map[string]map[string]string, emailSubjectTmpl, emailBodyTmpl, replyToEmail, senderDisplayName string) {
	//line emails.apex.hbs.qtpl:1
	qw422016.N().S(`
// BEGIN auto-generated Apex code (https://github.com/grokify/go-salesforce/apex)
String emailSubjectTmpl = '`)
	//line emails.apex.hbs.qtpl:3
	qw422016.N().S(EscapeSingleQuote(emailSubjectTmpl))
	//line emails.apex.hbs.qtpl:3
	qw422016.N().S(`';
String emailBodyTmpl = '`)
	//line emails.apex.hbs.qtpl:4
	qw422016.N().S(EscapeSingleQuote(emailBodyTmpl))
	//line emails.apex.hbs.qtpl:4
	qw422016.N().S(`';
String replyToEmail = '`)
	//line emails.apex.hbs.qtpl:5
	qw422016.N().S(EscapeSingleQuote(replyToEmail))
	//line emails.apex.hbs.qtpl:5
	qw422016.N().S(`';
String senderDisplayName = '`)
	//line emails.apex.hbs.qtpl:6
	qw422016.N().S(EscapeSingleQuote(senderDisplayName))
	//line emails.apex.hbs.qtpl:6
	qw422016.N().S(`';

Map<String,Map<String,String>> emailsData = `)
	//line emails.apex.hbs.qtpl:8
	qw422016.N().S(MapStringMapStringStringToApex(data, true))
	//line emails.apex.hbs.qtpl:8
	qw422016.N().S(`;

List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

for (String key : emailsData.keySet()) {
  Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
  
  Map<String,String> emailData = emailsData.get(key);

  String emailSubject = emailSubjectTmpl;
  String emailBody = emailBodyTmpl;

  for (String emailTmplKey : emailData.keySet()) {
    String emailTmplVal = emailData.get(emailTmplKey);

    Integer lastChar = emailTmplKey.charAt(emailTmplKey.length()-1);

    if (lastChar != 95) {
      emailSubject = emailSubject.replace('{{'+emailTmplKey+'}}', emailTmplVal);
      emailBody = emailBody.replace('{{'+emailTmplKey+'}}', emailTmplVal);
    }
  }

  Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

  String sendTo = emailData.get('to_');
  if (string.isNotBlank(sendTo)) {
    email.setToAddresses(sendTo.split(';'));
    String sendCc = emailData.get('cc_');
    if (string.isNotBlank(sendCc)) {
      email.setCcAddresses(sendCc.split(';'));
    }
    String sendBcc = emailData.get('bcc_');
    if (string.isNotBlank(sendBcc)) {
      email.setBccAddresses(sendBcc.split(';'));
    }
    if (string.isNotBlank(replyToEmail)) {
      email.setReplyTo(replyToEmail);
    }
    if (string.isNotBlank(senderDisplayName)) {
      email.setSenderDisplayName(senderDisplayName);    
    }
    email.setSubject(emailSubject);
    email.setHtmlBody(emailBody);
    emails.add(email);
  }
}

if (emails.size()>0) {
  Messaging.sendEmail(emails);
}
// END auto-generated Apex code (https://github.com/grokify/go-salesforce/apex)
`)
//line emails.apex.hbs.qtpl:60
}

//line emails.apex.hbs.qtpl:60
func WriteApexEmailsTemplate(qq422016 qtio422016.Writer, data map[string]map[string]string, emailSubjectTmpl, emailBodyTmpl, replyToEmail, senderDisplayName string) {
	//line emails.apex.hbs.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line emails.apex.hbs.qtpl:60
	StreamApexEmailsTemplate(qw422016, data, emailSubjectTmpl, emailBodyTmpl, replyToEmail, senderDisplayName)
	//line emails.apex.hbs.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line emails.apex.hbs.qtpl:60
}

//line emails.apex.hbs.qtpl:60
func ApexEmailsTemplate(data map[string]map[string]string, emailSubjectTmpl, emailBodyTmpl, replyToEmail, senderDisplayName string) string {
	//line emails.apex.hbs.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
	//line emails.apex.hbs.qtpl:60
	WriteApexEmailsTemplate(qb422016, data, emailSubjectTmpl, emailBodyTmpl, replyToEmail, senderDisplayName)
	//line emails.apex.hbs.qtpl:60
	qs422016 := string(qb422016.B)
	//line emails.apex.hbs.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
	//line emails.apex.hbs.qtpl:60
	return qs422016
//line emails.apex.hbs.qtpl:60
}
