// This file is automatically generated by qtc from "map.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line map.qtpl:1
package apex

//line map.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line map.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line map.qtpl:1
func StreamMapStringStringToApex(qw422016 *qt422016.Writer, data map[string]string, initialize bool) {
	//line map.qtpl:1
	if initialize {
		//line map.qtpl:1
		qw422016.N().S(`new Map<String, String> `)
		//line map.qtpl:1
	}
	//line map.qtpl:1
	qw422016.N().S(`{`)
	//line map.qtpl:2
	l := len(data)
	i := 0

	//line map.qtpl:4
	for key, val := range data {
		//line map.qtpl:4
		qw422016.N().S(`'`)
		//line map.qtpl:4
		qw422016.N().S(EscapeSingleQuote(key))
		//line map.qtpl:4
		qw422016.N().S(`' => '`)
		//line map.qtpl:4
		qw422016.N().S(EscapeSingleQuote(val))
		//line map.qtpl:4
		qw422016.N().S(`'`)
		//line map.qtpl:5
		i += 1

		//line map.qtpl:6
		if i < l {
			//line map.qtpl:6
			qw422016.N().S(`,`)
			//line map.qtpl:6
		}
		//line map.qtpl:6
	}
	//line map.qtpl:6
	qw422016.N().S(`}`)
//line map.qtpl:6
}

//line map.qtpl:6
func WriteMapStringStringToApex(qq422016 qtio422016.Writer, data map[string]string, initialize bool) {
	//line map.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line map.qtpl:6
	StreamMapStringStringToApex(qw422016, data, initialize)
	//line map.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line map.qtpl:6
}

//line map.qtpl:6
func MapStringStringToApex(data map[string]string, initialize bool) string {
	//line map.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
	//line map.qtpl:6
	WriteMapStringStringToApex(qb422016, data, initialize)
	//line map.qtpl:6
	qs422016 := string(qb422016.B)
	//line map.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
	//line map.qtpl:6
	return qs422016
//line map.qtpl:6
}

//line map.qtpl:8
func StreamMapStringMapStringStringToApex(qw422016 *qt422016.Writer, data map[string]map[string]string, initialize bool) {
	//line map.qtpl:8
	if initialize {
		//line map.qtpl:8
		qw422016.N().S(`new Map<String,Map<String,String>> `)
		//line map.qtpl:8
	}
	//line map.qtpl:8
	qw422016.N().S(`{`)
	//line map.qtpl:9
	l := len(data)
	i := 0

	//line map.qtpl:11
	for key, val := range data {
		//line map.qtpl:11
		qw422016.N().S(`'`)
		//line map.qtpl:11
		qw422016.N().S(EscapeSingleQuote(key))
		//line map.qtpl:11
		qw422016.N().S(`' => `)
		//line map.qtpl:11
		qw422016.N().S(MapStringStringToApex(val, true))
		//line map.qtpl:12
		i += 1

		//line map.qtpl:13
		if i < l {
			//line map.qtpl:13
			qw422016.N().S(`,`)
			//line map.qtpl:13
		}
		//line map.qtpl:13
	}
	//line map.qtpl:13
	qw422016.N().S(`}`)
//line map.qtpl:13
}

//line map.qtpl:13
func WriteMapStringMapStringStringToApex(qq422016 qtio422016.Writer, data map[string]map[string]string, initialize bool) {
	//line map.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line map.qtpl:13
	StreamMapStringMapStringStringToApex(qw422016, data, initialize)
	//line map.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line map.qtpl:13
}

//line map.qtpl:13
func MapStringMapStringStringToApex(data map[string]map[string]string, initialize bool) string {
	//line map.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line map.qtpl:13
	WriteMapStringMapStringStringToApex(qb422016, data, initialize)
	//line map.qtpl:13
	qs422016 := string(qb422016.B)
	//line map.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line map.qtpl:13
	return qs422016
//line map.qtpl:13
}
